
# site variables. site.var

title: "공부하는 하루"
subtitle: "매일매일 조금씩 공부해보자"
email: "blogharu@gmail.com"
baseurl: ""
url: "https://blogharu.github.io"

# plugins

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap


# settings

# site collections
collections:
  cs:
    output: true
  mth:
    output: false
  mus:
    output: false

# default variables
defaults:
  # Set Category
  - scope:
      path: ""
      type: "cs"
    values:
      category: "cs"
      layout: "post"
  - scope:
      path: ""
      type: "mth"
    values:
      category: "mth"
  - scope:
      path: ""
      type: "mus"
    values:
      category: "mus"

  # Set Subcategory
  - scope:
      path: "_cs/atom"
    values:
      subcategory: "atom"
  - scope:
      path: "_cs/general"
    values:
      subcategory: "general"
  - scope:
      path: "_cs/jekyll"
    values:
      subcategory: "jekyll"
  - scope:
      path: "_cs/yaml"
    values:
      subcategory: "yaml"
