
# site variables. site.var

title: "공부하는 하루"
subtitle: "매일매일 조금씩 공부해보자"
email: "blogharu@gmail.com"
baseurl: ""
url: "https://blogharu.github.io"

# site collections

collections:
  cs:
    output: true
  math:
    output: false
  music:
    output: false

# default variables
defaults:
 - scope:
    path: ""
    type: "cs"
   values:
    hi: hi


# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
