
# site variables. site.var

title: "공부하는 하루"
subtitle: "컴퓨터를 공부해보자"
email: "blogharu@gmail.com"
baseurl: ""
url: "https://blogharu.github.io"

# site collections

collections:
  cs:
    output: true
  math:
    output: false

# plugins
plugins:
  - jekyll-seo-tag
